
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.flake8]
max-line-length = 88
exclude = ["venv", "__pycache__"]

[tool.pytest.ini_options]
testpaths = ["tests"]
